import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import HeroSection from "@/components/sections/HeroSection";
import AboutSection from "@/components/sections/AboutSection";
import ExploreSection from "@/components/sections/ExploreSction";
import WorkSection from "@/components/sections/WorkSection";
import WhateNewSection from "@/components/sections/WhateNewSection";
import WorldSection from "@/components/sections/WorldSection";
import InsightSection from "@/components/sections/InsightSection";
import FeedbackSection from "@/components/sections/FeedBackSection";
import FooterSection from "@/components/sections/FooterSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Metaversus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#19222d]  font-sans text-white pb-5">
        <Navbar />

        <HeroSection />
        <AboutSection />
        <ExploreSection />
        <WorkSection />
        <WhateNewSection />
        <WorldSection />
        <InsightSection />
        <FeedbackSection />
        <FooterSection />
      </main>
    </>
  );
}
